apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayBackend
metadata:
  name: qwen25-vl-instruct-agentgateway-backend
  namespace: agentgateway-system
spec:
  ai:
    provider:
      openai:
        model: qwen25-vl-instruct
        host: qwen25-vl-3b-service.vllm.svc.cluster.local
        port: 80